name = "TheAlgorithms"
uuid = "e4253e37-a807-4a6a-91a4-87b21ad1f734"
authors = ["Panquesito7"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
